name: Execute linter.yml located in main

on:
  push:
    branches: ["code-development"]

jobs:
  trigger_main_linter:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Trigger Main Linter Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Linter.yml
          ref: main
          repository: ${{ github.repository }}
