---
name: "Production Tests"  # code-production

on:
  workflow_run:
    workflows: "Staging Tests"
    types:
      - completed

jobs:
  deploy-to-staging:
    runs-on: ubuntu-latest
    steps:
    - name: Log Timestamp
      run: date
     
    - name: Checkout code
      uses: actions/checkout@v3.5.3

    - name: Download build artifact
      uses: actions/download-artifact@v2
      with:
        name: staging-artifact
        path: ./publish
