---
name: "Success"

# Development Environment (code-development) Tests

on:
  repository_dispatch:
    types: "trigger-success"

env:
  PROJ_NAME: "Blazor-SqLite-Golf-Club"

jobs:

  succeed:

    name: Success
    runs-on: ubuntu-latest
    timeout-minutes: 15


    strategy:
      matrix:
        test_framework: [Nunit, Xunit]

    steps:

    - name: Report SHA
      run: |
        echo "${{ github.event.client_payload.sha }}"
        date
