---
name: "Production Tests"
# Production Environment (code-production) Test Suite

on:
  repository_dispatch:
    types: "trigger-development-tests"

env:
  PROJ_NAME: "Blazor-SqLite-Golf-Club"

jobs:

  production-testing:
  
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: (github.actor != 'CodeApprover')

    environment:
      production

    steps:
    
    - name: Report SHA and workflow timestamp
      run: |
        echo "${{ github.event.client_payload.sha }}"
        date
 
