---
name: "Staging Tests"

# Production Environment: code-production

on:
  workflow_run:
    workflows:
      - Development
    types:
      - success

jobs:
  deploy-to-production:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    environment:
      staging

    steps:
    
    - name: Report SHA and workflow timestamp
      run: |
        echo "${{ github.event.client_payload.sha }}"
        date
 
